name: DevContainer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and test devcontainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: web3-devcontainer-minimal
        cacheFrom: web3-devcontainer-minimal
        push: never
        runCmd: |
          echo "Testing devcontainer build..."
          node --version
          npm --version
          which forge || echo "Forge not found"
          which cast || echo "Cast not found"
          which anvil || echo "Anvil not found"